# Generated by Django 5.0 on 2024-01-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="club",
            field=models.ManyToManyField(to="blog.club"),
        ),
    ]
