# Generated by Django 5.0 on 2024-01-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="banner",
            field=models.ImageField(
                default="default_book.jpg", upload_to="profile_pics"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="current_book",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
