# Generated by Django 5.1.4 on 2024-12-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_club_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='banner',
            field=models.ImageField(default='default-icon.jpg', upload_to='profile_pics'),
        ),
    ]
