# Generated by Django 5.1.4 on 2024-12-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_club_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='banner',
            field=models.ImageField(default='profile_pics/default-icon.jpg', upload_to='profile_pics'),
        ),
    ]
