# Generated by Django 5.1.4 on 2024-12-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_club_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='banner',
            field=models.ImageField(default='profile_pics/default-club_iFCZdbI.jpg', upload_to='profile_pics'),
        ),
    ]
